### ISSUE TITLE
grindencoder- exension build failure

### ISSUE THREAD

**Issue by roshanpuru** [ashawkey/nerf2mesh#1]
error: no instance of overloaded function "atomicAdd" matches the argument list

**Comment by ashawkey** [comment]
@roshanpuru Unfortunately, that indicates the GPU architecture is too old and not supported. You'll need at least [SM_70](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/) to use the CUDA extensions.

**Comment by roshanpuru** [comment]
> @roshanpuru Unfortunately, that indicates the GPU architecture is too old and not supported. You'll need at least [SM_70](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/) to use the CUDA extensions.

True, found out that addAtomic uses Hardware logic gates for computation, move to new gpu compute arch to solve it.
