### ISSUE TITLE
depth supervision

### ISSUE THREAD

**Issue by cv-lab-x** [ashawkey/nerf2mesh#10]
hi, thanks for your great work! there'are some questions about the depth supervision.
1.have your test your codes on depth supervision, your didn't mention any experiments about depth in your paper?
2.how did your train with depth supervision, because the depth map size is 384*384, while your training  image size is different?
3.have your trained with depth supervision on some outdoor datasets, and did the depth supervision work well, cause the mono depth estimation on outdoor scenes are not good  especially on plants 

looking forward to your reply, thanks! @ashawkey

**Comment by ashawkey** [comment]
@cv-lab-x Hi, yes, depth supervision is an optional feature and I don't perform extensive experiments.
We simply resize the depth map. From my experience, depth supervision is not very effective if there are enough views to train, like the three datasets we used.
