### ISSUE TITLE
Synthetic dataset meshes

### ISSUE THREAD

**Issue by zarzarj** [ashawkey/nerf2mesh#12]
Hi,

Where is it possible to download the ground truth synthetic dataset meshes?

**Comment by ashawkey** [comment]
@zarzarj Hi, you could download the blender files [here](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) and export them to mesh.

**Comment by zarzarj** [comment]
Thank you very much!
