### ISSUE TITLE
Two meshes have been saved in stage1

### ISSUE THREAD

**Issue by JI0726** [ashawkey/nerf2mesh#18]
Thanks  a lot for your great work!
But I'ev encountered an issue that if I change the --scale from 0.8（which is the default setting） to 1 I will get two separate meshes in /nerf2mesh-main/lego_scale1box2/mesh_stage1/.And these two separate meshes can be merged into a full mesh which is exactly the mesh for the object.

**Comment by ashawkey** [comment]
@JI0726 I guess you are using `bound > 1`? In that case, we would export multiple meshes located in different bounding boxes. But for the synthetic dataset, `bound = 1` is enough.

**Comment by JI0726** [comment]
Thanks for your kind reply. Yes, I set bound > 1 because the camera position is not scaled under my method, so bounding box=1 will cause it to be too small for the synthetic lego scenes.
