### ISSUE TITLE
Saving Mesh Failed

### ISSUE THREAD

**Issue by roshanpuru** [ashawkey/nerf2mesh#20]
First of all great job.

I used colmap and ran the following command:  python3 main.py plant/ --workspace plant-output  -O --data_format colmap --bound 1 --scale 0.3 --stage 0 --clean_min_f 16 --clean_min_d 10 --lambda_tv 2e-8 --visibility_mask_dilation 10 --decimate_target 500000

But got below error.

  File "/home/ubuntu/nerf2mesh/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 248, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 700[cudaMemcpyAsync(&atomics[0], m_crAtomics.getPtr(), sizeof(CRAtomics) * m_numImages, cudaMemcpyDeviceToHost, stream);]

**Comment by ashawkey** [comment]
@roshanpuru Hi, it seems to be an error related to [nvdiffrast](https://github.com/NVlabs/nvdiffrast), could you try their examples?

**Comment by DavidCao1993** [comment]
@roshanpuru, I meet the same problem, how do you solved it?
