### ISSUE TITLE
 the result of forward-facing captures is bad

### ISSUE THREAD

**Issue by Gary-Qinghua** [ashawkey/nerf2mesh#23]
I had a problem running the dinosaur picture. My results are very poor!
The command lines run in the following order:
python scripts/colmap2nerf.py --images ./data/dragon/images/ --run_colmap
python scripts/downscale.py data/dragon --downscale 4
python main.py data/dragon/ --workspace trial_dragon -O --data_format colmap --bound 4 --scale 0.3 --downscale 4 --stage 0 --clean_min_f 16 --clean_min_d 10 --lambda_tv 2e-8 --visibility_mask_dilation 50
![DJI_20200223_163016_842](https://user-images.githubusercontent.com/73276075/231956213-889bf60a-7bfd-4464-949c-5f1cbbacf7bf.jpg)
![20230414141153](https://user-images.githubusercontent.com/73276075/231956389-0cf70cb2-7886-4889-bbac-8638f8098685.png)

**Comment by ashawkey** [comment]
@Gary-Qinghua Hi, please use the following command from `scripts` for LLFF datasets:
```
python main.py data/nerf_llff_data/horns --workspace trial_llff_horns -O --data_format colmap --bound 4 --downscale 4 --stage 0 --visibility_mask_dilation 50
python main.py data/nerf_llff_data/horns --workspace trial_llff_horns -O --data_format colmap --bound 4 --downscale 4 --stage 1 --iters 10000
```
I guess the `scale` of your setting is improper.

**Comment by Gary-Qinghua** [comment]
Thanks for your quick reply!
It's work now.
