### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by tsugg** [ashawkey/nerf2mesh#3]
Hey, I gave this a shot yesterday and couldn't get it to run all the way through. On WSL I could get all the way through stage 0; however, OpenGL 4.2 is the latest version available on WSL so I couldn't try out stage 1. 

I switched over to straight up Windows and then the issue is building the extensions inside of nerf2mesh/ like raymarching/ and freqencoder/. I tried with different versions of python, torch, and cuda.

Each of the extensions failed with this error: 
and the typical "this is not a pip issue" or something like that

subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by ashawkey** [comment]
@tsugg Hi, unfortunately I don't have a Windows to test. Could you successfully to install other CUDA extensions, like [tiny-cuda-nn](https://github.com/NVlabs/tiny-cuda-nn)?

**Comment by r530044129** [comment]
I've meet the same problem, my window can't install raymarching, and I tried to install tiny-cuda-nn too, it's failed.
Error of Building raymaching:
![image](https://user-images.githubusercontent.com/22882223/227447558-ed60c7d9-8757-43b2-8699-1005db78ad57.png)

Error of Installing tiny-cuda-nn:
![image](https://user-images.githubusercontent.com/22882223/227447212-0ba46c69-b8f7-42c3-99be-bd0d0ce969fe.png)

**Comment by SavageChigga** [comment]
> I've meet the same problem, my window can't install raymarching, and I tried to install tiny-cuda-nn too, it's failed. Error of Building raymaching: ![image](https://user-images.githubusercontent.com/22882223/227447558-ed60c7d9-8757-43b2-8699-1005db78ad57.png)
> 
> Error of Installing tiny-cuda-nn: ![image](https://user-images.githubusercontent.com/22882223/227447212-0ba46c69-b8f7-42c3-99be-bd0d0ce969fe.png)

Hi, I had the same problems as in your screenshot, did you fix them later?
