### ISSUE TITLE
Hello, where can I download the mesh ground truth of the nerf synthetic dataset?

### ISSUE THREAD

**Issue by ZZy129326999** [ashawkey/nerf2mesh#43]
Hello, where can I download the mesh ground truth of the nerf synthetic dataset? Thank you very much!!!

**Comment by ZZy129326999** [comment]
![image](https://user-images.githubusercontent.com/72543018/236679299-fba8936f-895e-4b50-a872-b2f602ad88ac.png)
By blender ?

**Comment by ashawkey** [comment]
@ZZy129326999 Hi, yes, we export obj from the original blender project.

**Comment by ZZy129326999** [comment]
> @ZZy129326999 Hi, yes, we export obj from the original blender project.

Thank your perfect reply! Is the NeRF360 scene dataset without ground truth？Thank you very much !!

**Comment by ashawkey** [comment]
Yes.

**Comment by ZZy129326999** [comment]
Thank you very much! Good Luck!!
