### ISSUE TITLE
 " running: mkdir data/custom\colmap_text   FATAL: command failed" at step 1，how can i fix it?

### ISSUE THREAD

**Issue by ahfangming** [ashawkey/nerf2mesh#49]
Elapsed time: 1.276 [minutes]
==== running: mkdir data/custom\colmap_text
命令语法不正确。
FATAL: command failed

**Comment by ashawkey** [comment]
@ahfangming Hi, are you using Windows? We only support linux now, but you can fix this by fixing the slash/backslash.

**Comment by ahfangming** [comment]
@ashawkey I see, thank you very much, I'll try again
