### ISSUE TITLE
Question for using multi GPU

### ISSUE THREAD

**Issue by LyndzP** [ashawkey/nerf2mesh#50]
Hi Thank you for amazing project for everyone.
I have a question for generating mesh speed with multi GPU

I guess the network using only 1 GPU for generating mesh, so Is there any way to use multi GPU for processing? 
In my env, It spends 20mins for processing stage 1,2 (RTX 4090)
I just want to make more faster to generate mesh from NeRF. any solutions?

Thanks

**Comment by LyndzP** [comment]
I found the code use torch.nn.parallel.DistributedDataParallel in utils.py 521
So I set init_process_group like this. 
`model.to(self.device)
        if self.world_size > 1:
            dist.init_process_group(backend='nccl',init_method='tcp://127.0.0.1:23456',rank=0, world_size=self.world_size)
            model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
            model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank])`

But the process was stop. Can I get some solution?

**Comment by ashawkey** [comment]
@LyndzP Hi, sorry that multi-GPU is not yet supported for now.
