### ISSUE TITLE
the mesh of my own data is bad

### ISSUE THREAD

**Issue by Gary-Qinghua** [ashawkey/nerf2mesh#61]
Hi, thanks for your help earlier. I have runned this project on the data you provided, and the result is well.
But for my own data, it doesn't work very well.
My command line is:
CUDA_VISIBLE_DEVICES=5 python main.py data/yuanshen/ --workspace trial_360_yuanshen -O --data_format colmap --bound 2 --enable_cam_center --enable_cam_near_far --scale 0.4 --stage 0 --lambda_entropy 1e-3 --clean_min_f 16 --clean_min_d 10 --lambda_tv 2e-8 --visibility_mask_dilation 50
I uploaded my data, can you give me some advice, thanks!
[yuanshen.zip](https://github.com/ashawkey/nerf2mesh/files/11703177/yuanshen.zip)
![微信图片_20230609151804](https://github.com/ashawkey/nerf2mesh/assets/73276075/16f1a127-ac31-4502-963d-66e0cac72b27)

**Comment by ashawkey** [comment]
@Gary-Qinghua Hi, I guess you'll want to try the SDF mode for single-object reconstruction. The scale and bound may need to be adjusted. Also, many photos are sufferring from motion-blur. You may follow the data capture advice [here](https://docs.lumalabs.ai/MCrGAEukR4orR9).

**Comment by Gary-Qinghua** [comment]
Thanks.  I tried SDF mode, but it seems less effective. What you said should be right. I will collect again according to your advice. 
I have another question about the mesh quality.  Due to the large number of spikes, the result of stage0 looks better than stage1. Why?
Can I not use this function "refine_and_decimate " in stage1?

**Comment by Gary-Qinghua** [comment]
https://github.com/ashawkey/nerf2mesh/assets/73276075/26872268-c714-4f83-b015-902d6619a0b0


https://github.com/ashawkey/nerf2mesh/assets/73276075/2d15b4b5-50cf-4e66-8be5-4477497647aa

**Comment by ashawkey** [comment]
Yes, and that's what SDF mode will do. I guess you should apply background removal for SDF mode.

**Comment by Gary-Qinghua** [comment]
If you just reconstruct a single object, a lot of tasks can be done. I think getting the mesh of scene is the highlight of your project. The results on the data of MIP-NERF-360 are very good.

**Comment by ashawkey** [comment]
In that case you may try to set `opt.refine = False` manually, or increase `--lambda_normal` to a very high value like 0.1. Actually SDF mode can somewhat work for scene reconstruction now, you could also give it a try. If the model won't converge, you can try to turn on '--enable_dense_depth'.

**Comment by Gary-Qinghua** [comment]
I will try. Thanks!
