### ISSUE TITLE
The reconstruction quality of garden dataset is bad by using the script of scripts\runall_360_outdoor.sh

### ISSUE THREAD

**Issue by HarshWinterBytes** [ashawkey/nerf2mesh#63]
Hello, thank you for doing such amazing work.
However, when I reproduced the results of the garden dataset, I found that the reconstructed results were very poor. I'm not sure which step of my operation is wrong. Here is the validation result during training I got:
![ngp_stage1_ep0063_0024_rgb](https://github.com/ashawkey/nerf2mesh/assets/65087973/b7a91d2d-5923-4aa8-a927-9eaa560730e1)
picture name: ngp_stage1_ep0063_0024_rgb.png

And here is the mesh:
![snapshot00](https://github.com/ashawkey/nerf2mesh/assets/65087973/72c6cfa9-2e4a-4774-9eb4-486ae5f39876)

And the scripts I use are here:
`CUDA_VISIBLE_DEVICES=0 python main.py data/garden/ --workspace trial_360_garden   -O --data_format colmap --bound 16 --enable_cam_center --enable_cam_near_far --scale 0.3 --downscale 4 --stage 0 --lambda_entropy 1e-3 --clean_min_f 16 --clean_min_d 10 --visibility_mask_dilation 50
`
`
CUDA_VISIBLE_DEVICES=0 python main.py data/garden/ --workspace trial_360_garden   -O --data_format colmap --bound 16 --enable_cam_center --enable_cam_near_far --scale 0.3 --downscale 4 --stage 1 --iters 10000
`
For the garden dataset, I downloaded it and used it directly without making any changes. And I see that someone in issue has successfully reconstructed good quality results with the garden dataset. So I would really like to know where I made a mistake.
Looking forward to your or others' reply.

**Comment by HarshWinterBytes** [comment]
In addition, the program runs on the following environment:
`Windows 10 + CUDA 11.3 + pytorch 1.10 + python 3.8`

Also, I noticed that during the training process, the program gave a warning that the data was not aligned！I'm not sure if this warning is what caused my results to be so bad.

**Comment by Gary-Qinghua** [comment]
Use SDF mode.  Try runall_outdoor_sdf.sh.
Since the SDF update, non-SDF modes are no longer available

**Comment by Seiano** [comment]
can't find the 'runall_outdoor_sdf.sh' file.

**Comment by LiuShuai086** [comment]
I find the sdf mode works worse than non-sdf mode, could you give me some adivce about how to get better results under the sdf mode? @Gary-Qinghua
